[package]
name = "avs-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0"
memmap = "0"
# dlopen = "0.1"
avs-binding-macros = { path = "avs-binding-macros" }

[build-dependencies]
bindgen = "0"
cmake = "0"
